_wandb:
    value:
        cli_version: 0.21.3
        e:
            e8bw5154jocxxekvyy0p6ent6cdaj5sn:
                args:
                    - --max_steps
                    - "50"
                    - --save_steps
                    - "25"
                codePath: main_hf_trl_dapo_v2_fsdp.py
                codePathLocal: main_hf_trl_dapo_v2_fsdp.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "520120602624"
                        used: "271599501312"
                email: rladbsgh797210@gmail.com
                executable: /home/ubuntu/miniconda3/envs/gpt-oss/bin/python
                git:
                    commit: d0dbb8c605825e5b48442aab74fb3d4bef18c683
                    remote: https://github.com/iamseungpil/gpt-oss.git
                gpu: NVIDIA H200
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-44d38bf4-f52b-5cf9-cb78-0ecb85532d6f
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-7e117ab2-5fa7-b28a-da64-2969b81ee94b
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-946331af-e1b7-04ca-d5b7-0465266adf65
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-8f0f6acf-ef28-0d81-6e52-0387909a3442
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-bf05a520-c153-ab29-88cd-c88dc3799821
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-1eafdc55-218b-32fd-808b-c1613f36c543
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-53ef3bb1-6c3a-20b1-d57b-5f99a5f07f05
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-2744f889-38f0-a3bd-d9ba-f5ad3b2fed78
                host: ip-10-10-28-56
                memory:
                    total: "2147425345536"
                os: Linux-6.8.0-1029-aws-x86_64-with-glibc2.35
                program: /home/ubuntu/gpt-oss/main_hf_trl_dapo_v2_fsdp.py
                python: CPython 3.10.18
                root: /home/ubuntu/gpt-oss
                startedAt: "2025-09-05T13:33:09.480653Z"
                writerId: e8bw5154jocxxekvyy0p6ent6cdaj5sn
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
                - 84
                - 98
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.21.3
            "6": 4.56.1
            "12": 0.21.3
            "13": linux-x86_64
continual_learning:
    value: true
dataset_size:
    value: 10
fsdp_enabled:
    value: true
max_tokens:
    value: 30000
memory_optimized:
    value: true
method:
    value: HF TRL GRPO/DAPO
model:
    value: openai/gpt-oss-20b
reward_components:
    value: 5
steps_per_problem:
    value: 50
world_size:
    value: 2
